#!/usr/bin/env node
/**
 * Build audit — the checks that can only run on the finished output.
 *
 *   npm run check:build      (after npm run build)
 *
 * `astro check` reads the source and finds type errors. This reads `dist/`
 * and finds the things that are only wrong once everything is assembled: a
 * link to a route that no longer exists, a heading level skipped because a
 * component was reused under a different parent, a draft that escaped, a
 * placeholder that shipped.
 *
 * Every one of these has a real failure mode behind it — see the note on each
 * check. Nothing here is a style preference.
 *
 * No dependencies, on purpose: this file has to keep working when the toolchain
 * moves. The HTML it parses is generated by one build, so regexes are safe in a
 * way they would never be against hand-written markup.
 *
 * Exit code 1 if anything fails, so it can gate a deploy.
 */

import { readdir, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join, relative, sep } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
/* An explicit path is for testing the checks themselves: copy dist/, break
   something in the copy, and confirm the right check goes red. A suite that
   has never failed is not known to work. */
const DIST = process.argv[2] ? resolve(process.argv[2]) : resolve(HERE, '..', 'dist');

const RED = '\x1b[31m';
const GREEN = '\x1b[32m';
const DIM = '\x1b[2m';
const BOLD = '\x1b[1m';
const OFF = '\x1b[0m';

if (!existsSync(DIST)) {
  console.error(`${RED}✗ No dist/ — run \`npm run build\` first.${OFF}`);
  process.exit(1);
}

/* ---------------------------------------------------------------------------
   Load the built site
   --------------------------------------------------------------------------- */

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

const allFiles = await walk(DIST);

/** '/blog/bert-from-scratch/' for dist/blog/bert-from-scratch/index.html */
function urlOf(file) {
  const rel = relative(DIST, file).split(sep).join('/');
  if (rel === 'index.html') return '/';
  if (rel.endsWith('/index.html')) return '/' + rel.slice(0, -'index.html'.length);
  return '/' + rel;
}

const pages = allFiles
  .filter((f) => f.endsWith('.html'))
  .map((f) => ({ file: f, url: urlOf(f), html: '' }));

for (const page of pages) page.html = await readFile(page.file, 'utf8');

/** Pages a reader navigates to. 404 is excluded from sitemap/link expectations. */
const routes = pages.filter((p) => p.url !== '/404.html' && p.url !== '/404/');

/* ---------------------------------------------------------------------------
   Reporting
   --------------------------------------------------------------------------- */

const results = [];
function check(name, why, failures) {
  results.push({ name, why, failures });
}

/** Strip <pre>/<code> so prose examples never trip a content check. */
function withoutCode(html) {
  return html.replace(/<pre[\s\S]*?<\/pre>/g, '').replace(/<code[\s\S]*?<\/code>/g, '');
}

/* ---------------------------------------------------------------------------
   1 — Exactly one <h1> per page
   A page with none is unlabelled to a screen reader and to Google; a page with
   two has no single answer to "what is this page".
   --------------------------------------------------------------------------- */
{
  const bad = [];
  for (const p of routes) {
    const n = (p.html.match(/<h1[\s>]/g) || []).length;
    if (n !== 1) bad.push(`${p.url} has ${n} <h1>`);
  }
  check('one <h1> per page', 'unlabelled or ambiguous page', bad);
}

/* ---------------------------------------------------------------------------
   2 — No skipped heading levels
   h1 -> h3 reads as a heading gone missing to anyone navigating by heading,
   which is how screen-reader users skim a list. This has broken once already,
   when PostRow's hard-coded <h3> was reused under an <h1> section.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  for (const p of routes) {
    const levels = [...p.html.matchAll(/<(h[1-6])[\s>]/g)].map((m) => +m[1][1]);
    let prev = 0;
    for (const lvl of levels) {
      if (prev && lvl > prev + 1) {
        bad.push(`${p.url} jumps h${prev} -> h${lvl}`);
        break;
      }
      prev = lvl;
    }
  }
  check('no skipped heading levels', 'broken document outline', bad);
}

/* ---------------------------------------------------------------------------
   3 — Every internal link resolves
   The single highest-value check here. Routes get renamed and links go stale
   silently; a static site 404s in production with nothing failing at build.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  const exists = (url) => {
    const clean = url.split('#')[0].split('?')[0];
    if (!clean || clean === '/') return existsSync(join(DIST, 'index.html'));
    const asFile = join(DIST, clean);
    if (existsSync(asFile) && !clean.endsWith('/')) return true;
    return existsSync(join(DIST, clean, 'index.html'));
  };

  for (const p of pages) {
    const hrefs = [...p.html.matchAll(/href="([^"]+)"/g)].map((m) => m[1]);
    for (const href of new Set(hrefs)) {
      if (/^(https?:|mailto:|tel:|data:|#|\/\/)/.test(href)) continue;
      if (!href.startsWith('/')) continue; // relative asset paths, rare here
      if (!exists(href)) bad.push(`${p.url} -> ${href}`);
    }
  }
  check('internal links resolve', 'dead link in production', bad);
}

/* ---------------------------------------------------------------------------
   4 — Every <img> carries alt
   alt="" is valid and means "decorative". A MISSING alt is the bug: a screen
   reader then reads the filename out loud.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  for (const p of routes) {
    for (const m of p.html.matchAll(/<img\b[^>]*>/g)) {
      if (!/\salt=/.test(m[0])) bad.push(`${p.url}: ${m[0].slice(0, 76)}`);
    }
  }
  check('every <img> has alt', 'screen reader reads the filename', bad);
}

/* ---------------------------------------------------------------------------
   5 — No drafts in the output
   draft:true is the only mechanism for unfinished work. If it leaks, the site
   publishes something that was meant to stay unpublished.
   --------------------------------------------------------------------------- */
{
  const src = resolve(HERE, '..', 'src', 'content');
  const drafts = [];
  for (const dir of ['blog', 'work']) {
    const d = join(src, dir);
    if (!existsSync(d)) continue;
    for (const f of await readdir(d)) {
      if (!/\.mdx?$/.test(f)) continue;
      const body = await readFile(join(d, f), 'utf8');
      const fm = body.split(/^---$/m)[1] ?? '';
      if (/^\s*draft:\s*true\s*$/m.test(fm)) drafts.push(f.replace(/\.mdx?$/, ''));
    }
  }
  const bad = [];
  for (const id of drafts) {
    if (routes.some((p) => p.url.includes(`/${id}/`))) bad.push(`draft published: ${id}`);
    for (const p of routes) {
      if (p.html.includes(`/blog/${id}/`)) bad.push(`${p.url} links to draft ${id}`);
    }
  }
  check(
    `no drafts in output ${DIM}(${drafts.length} draft${drafts.length === 1 ? '' : 's'})${OFF}`,
    'unfinished work published',
    bad
  );
}

/* ---------------------------------------------------------------------------
   6 — No placeholders in the output
   filled() strips TODO strings in production. If one reaches dist/, that
   guard has been bypassed somewhere.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  for (const p of routes) {
    if (/TODO/.test(withoutCode(p.html))) bad.push(`${p.url} contains "TODO"`);
  }
  check('no TODO placeholders shipped', 'unfilled placeholder visible to readers', bad);
}

/* ---------------------------------------------------------------------------
   7 — Every route is in the sitemap
   A page absent from the sitemap is a page that may never be indexed.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  const smFiles = allFiles.filter((f) => /sitemap.*\.xml$/.test(f));
  if (smFiles.length === 0) {
    bad.push('no sitemap found');
  } else {
    let xml = '';
    for (const f of smFiles) xml += await readFile(f, 'utf8');
    for (const p of routes) {
      // The sitemap holds absolute URLs; match on the path portion.
      const path = p.url === '/' ? '/' : p.url;
      const needle =
        path === '/'
          ? /<loc>[^<]*\/<\/loc>/
          : new RegExp(`<loc>[^<]*${path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}</loc>`);
      if (!needle.test(xml)) bad.push(`missing from sitemap: ${p.url}`);
    }
  }
  check('every route in the sitemap', 'page never indexed', bad);
}

/* ---------------------------------------------------------------------------
   8 — RSS points at pages that exist
   A feed is consumed by machines that will not forgive a 404, and readers see
   it long after the site changed.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  const feed = allFiles.find((f) => f.endsWith('rss.xml'));
  if (!feed) {
    bad.push('no rss.xml');
  } else {
    const xml = await readFile(feed, 'utf8');
    const links = [...xml.matchAll(/<link>([^<]+)<\/link>/g)].map((m) => m[1]);
    for (const link of links) {
      let path;
      try {
        path = new URL(link).pathname;
      } catch {
        continue;
      }
      if (path === '/') continue;
      if (!existsSync(join(DIST, path, 'index.html')) && !existsSync(join(DIST, path))) {
        bad.push(`feed links to missing ${path}`);
      }
    }
  }
  check('RSS links resolve', 'feed subscribers hit a 404', bad);
}

/* ---------------------------------------------------------------------------
   9 — One canonical per page, and it matches the page's own URL
   A canonical pointing elsewhere tells Google to index the other page instead.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  for (const p of routes) {
    const found = [
      ...p.html.matchAll(/<link[^>]+rel="canonical"[^>]*href="([^"]+)"/g),
    ].map((m) => m[1]);
    if (found.length !== 1) {
      bad.push(`${p.url} has ${found.length} canonical tags`);
      continue;
    }
    let path;
    try {
      path = new URL(found[0]).pathname;
    } catch {
      bad.push(`${p.url} canonical is not absolute: ${found[0]}`);
      continue;
    }
    const norm = (u) => (u.endsWith('/') ? u : u + '/');
    if (norm(path) !== norm(p.url)) bad.push(`${p.url} canonical -> ${path}`);
  }
  check('canonical matches its page', 'search engine indexes the wrong URL', bad);
}

/* ---------------------------------------------------------------------------
   10 — target="_blank" always carries rel=noopener
   Without it the opened page can reach back through window.opener. Base.astro
   adds this for the whole site; this check proves the script actually ran.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  for (const p of routes) {
    for (const m of p.html.matchAll(/<a\b[^>]*target="_blank"[^>]*>/g)) {
      if (!/rel="[^"]*noopener/.test(m[0])) bad.push(`${p.url}: ${m[0].slice(0, 90)}`);
    }
  }
  check('target=_blank has rel=noopener', 'reverse tabnabbing', bad);
}

/* ---------------------------------------------------------------------------
   11 — Unique, non-empty <title>
   Duplicated titles are the classic symptom of a layout prop not being passed,
   and they flatten every search result and browser tab.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  const seen = new Map();
  for (const p of routes) {
    const m = p.html.match(/<title>([\s\S]*?)<\/title>/);
    const title = m?.[1]?.trim();
    if (!title) {
      bad.push(`${p.url} has no <title>`);
      continue;
    }
    if (seen.has(title))
      bad.push(`${p.url} shares its title with ${seen.get(title)}: "${title}"`);
    else seen.set(title, p.url);
  }
  check('unique non-empty <title>', 'identical tabs and search results', bad);
}

/* ---------------------------------------------------------------------------
   12 — Non-empty meta description
   It is the snippet under the link, everywhere the page gets shared.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  for (const p of routes) {
    const m = p.html.match(/<meta\s+name="description"\s+content="([^"]*)"/);
    if (!m) bad.push(`${p.url} has no meta description`);
    else if (!m[1].trim()) bad.push(`${p.url} has an empty meta description`);
  }
  check('meta description present', 'blank share preview', bad);
}

/* ---------------------------------------------------------------------------
   13 — og:image exists on disk
   A share card that 404s is worse than none: the platform renders a grey box.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  for (const p of routes) {
    const m = p.html.match(/<meta\s+property="og:image"\s+content="([^"]+)"/);
    if (!m) {
      bad.push(`${p.url} has no og:image`);
      continue;
    }
    let path = m[1];
    try {
      path = new URL(m[1]).pathname;
    } catch {
      /* already a path */
    }
    if (!existsSync(join(DIST, path))) bad.push(`${p.url} og:image missing: ${path}`);
  }
  check('og:image exists', 'grey box when shared', bad);
}

/* ---------------------------------------------------------------------------
   14 — <html lang>
   Without it a screen reader reads English content in the user's own locale
   voice. One attribute, and WCAG 3.1.1 requires it.
   --------------------------------------------------------------------------- */
{
  const bad = [];
  for (const p of routes) {
    if (!/<html[^>]+\blang="[^"]+"/.test(p.html)) bad.push(`${p.url} has no <html lang>`);
  }
  check('<html lang> set', 'wrong screen-reader voice (WCAG 3.1.1)', bad);
}

/* ---------------------------------------------------------------------------
   Report
   --------------------------------------------------------------------------- */

console.log(
  `${BOLD}Build audit${OFF} ${DIM}· ${routes.length} pages · ${results.length} checks${OFF}\n`
);

let failed = 0;
for (const r of results) {
  if (r.failures.length === 0) {
    console.log(`${GREEN}✓${OFF} ${r.name}`);
  } else {
    failed++;
    console.log(`${RED}✗${OFF} ${BOLD}${r.name}${OFF} ${DIM}— ${r.why}${OFF}`);
    for (const f of r.failures.slice(0, 12)) console.log(`    ${RED}${f}${OFF}`);
    if (r.failures.length > 12)
      console.log(`    ${DIM}…and ${r.failures.length - 12} more${OFF}`);
  }
}

console.log('');
if (failed) {
  console.log(`${RED}${BOLD}✗ ${failed} of ${results.length} checks failed${OFF}`);
  process.exit(1);
}
console.log(`${GREEN}${BOLD}✓ All ${results.length} checks passed${OFF}`);
